/*
 * GameConfigurationException.java - created Aug 16, 2006 9:47:20 AM
 * $Id$
 */
package com.ourbabywolf.apples2apples;

/**
 * Indicates a mis-configuration of the game.
 * @author joe@ourbabywolf.com
 *
 */
public class GameConfigurationException extends RuntimeException {

	/**
	 * Generated by Eclipse.
	 */
	private static final long serialVersionUID = 1736643775691600613L;

	/**
	 * Creates a new exception.
	 * 
	 * @param configItemName - the name of the configuration item 
	 * 		(e.g. number of cards per hand)
	 * @param actualValue - the value set in the configuration
	 * @param minimumValue - the minimum allowed value
	 */
	public GameConfigurationException(String configItemName, 
			int actualValue, int minimumValue) {
		super(configItemName + " is set to " + actualValue
				+ ".  It cannot be set lower than " + minimumValue);
	}
	
	/**
	 * Creates a new exception pertaining to the number of points
	 * needed to win.
	 * 
	 * @param nbrOfPlayers - the number of players in the game
	 * @param actualValue - the value set in the configuration
	 * @param minimumValue - the minimum allowed value
	 */
	public GameConfigurationException(int nbrOfPlayers,
			int actualValue, int minimumValue) {
		super("The number of points to needed to win is set to " + actualValue
				+ " based on the current number of players, " + nbrOfPlayers
				+ ".  It cannot be set lower than " + minimumValue);
	}
}
